"""Add enum prospect_status

Revision ID: 09cc73c39830
Revises: 0f4568d667e1
Create Date: 2025-12-31 14:13:38.384248+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09cc73c39830'
down_revision: Union[str, Sequence[str], None] = '0f4568d667e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NEW', 'RESEARCHED', 'CONTACTED', 'ENGAGED', 'QUALIFIED', 'INACTIVE', name='prospect_status').create(op.get_bind())
    op.add_column('prospects', sa.Column('status', postgresql.ENUM('NEW', 'RESEARCHED', 'CONTACTED', 'ENGAGED', 'QUALIFIED', 'INACTIVE', name='prospect_status', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospects', 'status')
    sa.Enum('NEW', 'RESEARCHED', 'CONTACTED', 'ENGAGED', 'QUALIFIED', 'INACTIVE', name='prospect_status').drop(op.get_bind())
    # ### end Alembic commands ###
