"""Add enum types

Revision ID: 0f4568d667e1
Revises: 9ed0cc74125e
Create Date: 2025-12-31 13:15:57.991381+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f4568d667e1'
down_revision: Union[str, Sequence[str], None] = '9ed0cc74125e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('EMAIL', 'MEETING', 'CALL', 'EVENT', 'LINKEDIN', name='interaction_types').create(op.get_bind())
    sa.Enum('ON_DEMAND', 'SAVINGS_PLANS', 'RESERVED_INSTANCES', 'PROSERVE', 'SUBSCRIPTION', 'PPA', name='pricing_models').create(op.get_bind())
    op.alter_column('interactions', 'interaction_type',
               existing_type=sa.VARCHAR(length=255),
               type_=postgresql.ENUM('EMAIL', 'MEETING', 'CALL', 'EVENT', 'LINKEDIN', name='interaction_types'),
               existing_nullable=False,
               postgresql_using='interaction_type::interaction_types')
    op.alter_column('solutions', 'pricing_model',
               existing_type=sa.VARCHAR(length=255),
               type_=postgresql.ENUM('ON_DEMAND', 'SAVINGS_PLANS', 'RESERVED_INSTANCES', 'PROSERVE', 'SUBSCRIPTION', 'PPA', name='pricing_models'),
               existing_nullable=False,
               postgresql_using='pricing_model::pricing_models')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solutions', 'pricing_model',
               existing_type=postgresql.ENUM('ON_DEMAND', 'SAVINGS_PLANS', 'RESERVED_INSTANCES', 'PROSERVE', 'SUBSCRIPTION', 'PPA', name='pricing_models'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('interactions', 'interaction_type',
               existing_type=postgresql.ENUM('EMAIL', 'MEETING', 'CALL', 'EVENT', 'LINKEDIN', name='interaction_types'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    sa.Enum('ON_DEMAND', 'SAVINGS_PLANS', 'RESERVED_INSTANCES', 'PROSERVE', 'SUBSCRIPTION', 'PPA', name='pricing_models').drop(op.get_bind())
    sa.Enum('EMAIL', 'MEETING', 'CALL', 'EVENT', 'LINKEDIN', name='interaction_types').drop(op.get_bind())
    # ### end Alembic commands ###
