"""add indexes and vector tables

Revision ID: 4eb6dd6309d1
Revises: 79b596ca4cbc
Create Date: 2026-01-04 12:31:23.310323+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '4eb6dd6309d1'
down_revision: Union[str, Sequence[str], None] = '79b596ca4cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution_vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(384), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_solutions_embedding_hnsw', 'solution_vectors', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('interaction_vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(384), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interactions_embedding_hnsw', 'interaction_vectors', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_interactions_prospect_id'), 'interactions', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_logs_created_at'), 'llm_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_drafts_prospect_id'), 'outreach_drafts', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_prospect_research_prospect_id'), 'prospect_research', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_prospects_linkedin_url'), 'prospects', ['linkedin_url'], unique=True)
    op.create_index(op.f('ix_prospects_status'), 'prospects', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prospects_status'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_linkedin_url'), table_name='prospects')
    op.drop_index(op.f('ix_prospect_research_prospect_id'), table_name='prospect_research')
    op.drop_index(op.f('ix_outreach_drafts_prospect_id'), table_name='outreach_drafts')
    op.drop_index(op.f('ix_llm_usage_logs_created_at'), table_name='llm_usage_logs')
    op.drop_index(op.f('ix_interactions_prospect_id'), table_name='interactions')
    op.drop_index('ix_interactions_embedding_hnsw', table_name='interaction_vectors', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('interaction_vectors')
    op.drop_index('ix_solutions_embedding_hnsw', table_name='solution_vectors', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('solution_vectors')
    # ### end Alembic commands ###
