"""Update DB with OutreachDraft Enum type

Revision ID: 786fee35bdb7
Revises: 7ad88a02ed73
Create Date: 2026-01-11 13:53:48.895351+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '786fee35bdb7'
down_revision: Union[str, Sequence[str], None] = '7ad88a02ed73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CREATED', 'SENT', 'ACKNOWLEDGED', 'UNREAD', 'RESPONDED', 'DECLINED', name='outreach_status').create(op.get_bind())
    op.alter_column('outreach_drafts', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=postgresql.ENUM('CREATED', 'SENT', 'ACKNOWLEDGED', 'UNREAD', 'RESPONDED', 'DECLINED', name='outreach_status'),
               existing_nullable=False,
               postgresql_using='status::outreach_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outreach_drafts', 'status',
               existing_type=postgresql.ENUM('CREATED', 'SENT', 'ACKNOWLEDGED', 'UNREAD', 'RESPONDED', 'DECLINED', name='outreach_status'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    sa.Enum('CREATED', 'SENT', 'ACKNOWLEDGED', 'UNREAD', 'RESPONDED', 'DECLINED', name='outreach_status').drop(op.get_bind())
    # ### end Alembic commands ###
