"""Fix relationship error in industry_solutions


Revision ID: 79b596ca4cbc
Revises: 09cc73c39830
Create Date: 2025-12-31 16:37:12.007121+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b596ca4cbc'
down_revision: Union[str, Sequence[str], None] = '09cc73c39830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
