"""fix indexes and vector tables

Revision ID: 7ad88a02ed73
Revises: 4eb6dd6309d1
Create Date: 2026-01-04 13:03:12.421970+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad88a02ed73'
down_revision: Union[str, Sequence[str], None] = '4eb6dd6309d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
